swagger: '2.0'
info:
  description: Documentação da API de acesso aos endpoints do Ponto Inteligente 
  
  
    Para utilizar a API adequadamente deve-se acessar o seguinte serviço e conseguir um token enviando no body
    
    um email e senha válidos.
    
    
    POST https://calm-bastion-43271.herokuapp.com/auth
    
  version: '0.1'
  title: Ponto Inteligente API
host: 'calm-bastion-43271.herokuapp.com'
basePath: /
tags:
  - name: cadastro-pf-controller
    description: Cadastro PF Controller
  - name: lancamento-controller
    description: Lancamento Controller
  - name: cadastro-pj-controller
    description: Cadastro PJ Controller
  - name: funcionario-controller
    description: Funcionario Controller
  - name: empresa-controller
    description: Empresa Controller
paths:
  /api/cadastrar-pf:
    post:
      tags:
        - cadastro-pf-controller
      summary: cadastrar
      operationId: cadastrarUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: cadastroPFDto
          description: cadastroPFDto
          required: true
          schema:
            $ref: '#/definitions/CadastroPFDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«CadastroPFDto»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/cadastrar-pj:
    post:
      tags:
        - cadastro-pj-controller
      summary: cadastrar
      operationId: cadastrarUsingPOST_1
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: cadastroPJDto
          description: cadastroPJDto
          required: true
          schema:
            $ref: '#/definitions/CadastroPJDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«CadastroPJDto»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/empresas/{cnpj}':
    get:
      tags:
        - empresa-controller
      summary: buscarPorCnpj
      operationId: buscarPorCnpjUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: cnpj
          in: path
          description: cnpj
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«EmpresaDto»'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/funcionarios/{id}':
    put:
      tags:
        - funcionario-controller
      summary: atualizar
      operationId: atualizarUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - in: body
          name: funcionarioDto
          description: funcionarioDto
          required: true
          schema:
            $ref: '#/definitions/FuncionarioDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«FuncionarioDto»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/lancamentos:
    post:
      tags:
        - lancamento-controller
      summary: adicionar
      operationId: adicionarUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: lancamentoDto
          description: lancamentoDto
          required: true
          schema:
            $ref: '#/definitions/LancamentoDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«LancamentoDto»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/lancamentos/funcionario/{funcionarioId}':
    get:
      tags:
        - lancamento-controller
      summary: listarPorFuncionarioId
      operationId: listarPorFuncionarioIdUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: funcionarioId
          in: path
          description: funcionarioId
          required: true
          type: integer
          format: int64
        - name: pag
          in: query
          description: pag
          required: false
          type: integer
          default: 0
          format: int32
        - name: ord
          in: query
          description: ord
          required: false
          type: string
          default: id
        - name: dir
          in: query
          description: dir
          required: false
          type: string
          default: DESC
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«Page«LancamentoDto»»'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/api/lancamentos/{id}':
    get:
      tags:
        - lancamento-controller
      summary: listarPorId
      operationId: listarPorIdUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«LancamentoDto»'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - lancamento-controller
      summary: atualizar
      operationId: atualizarUsingPUT_1
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - in: body
          name: lancamentoDto
          description: lancamentoDto
          required: true
          schema:
            $ref: '#/definitions/LancamentoDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«LancamentoDto»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - lancamento-controller
      summary: remover
      operationId: removerUsingDELETE
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«string»'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
definitions:
  Optional«long»:
    type: object
    properties:
      present:
        type: boolean
  Optional«string»:
    type: object
    properties:
      present:
        type: boolean
  EmpresaDto:
    type: object
    properties:
      cnpj:
        type: string
      id:
        type: integer
        format: int64
      razaoSocial:
        type: string
  Response«Page«LancamentoDto»»:
    type: object
    properties:
      data:
        $ref: '#/definitions/Page«LancamentoDto»'
      errors:
        type: array
        items:
          type: string
  Response«string»:
    type: object
    properties:
      data:
        type: string
      errors:
        type: array
        items:
          type: string
  CadastroPJDto:
    type: object
    properties:
      cnpj:
        type: string
      cpf:
        type: string
      email:
        type: string
      id:
        type: integer
        format: int64
      nome:
        type: string
      razaoSocial:
        type: string
      senha:
        type: string
  Response«CadastroPJDto»:
    type: object
    properties:
      data:
        $ref: '#/definitions/CadastroPJDto'
      errors:
        type: array
        items:
          type: string
  LancamentoDto:
    type: object
    properties:
      data:
        type: string
      descricao:
        type: string
      funcionarioId:
        type: integer
        format: int64
      id:
        $ref: '#/definitions/Optional«long»'
      localizacao:
        type: string
      tipo:
        type: string
  Response«EmpresaDto»:
    type: object
    properties:
      data:
        $ref: '#/definitions/EmpresaDto'
      errors:
        type: array
        items:
          type: string
  Response«CadastroPFDto»:
    type: object
    properties:
      data:
        $ref: '#/definitions/CadastroPFDto'
      errors:
        type: array
        items:
          type: string
  CadastroPFDto:
    type: object
    properties:
      cnpj:
        type: string
      cpf:
        type: string
      email:
        type: string
      id:
        type: integer
        format: int64
      nome:
        type: string
      qtdHorasAlmoco:
        $ref: '#/definitions/Optional«string»'
      qtdHorasTrabalhoDia:
        $ref: '#/definitions/Optional«string»'
      senha:
        type: string
      valorHora:
        $ref: '#/definitions/Optional«string»'
  Response«LancamentoDto»:
    type: object
    properties:
      data:
        $ref: '#/definitions/LancamentoDto'
      errors:
        type: array
        items:
          type: string
  Response«FuncionarioDto»:
    type: object
    properties:
      data:
        $ref: '#/definitions/FuncionarioDto'
      errors:
        type: array
        items:
          type: string
  Page«LancamentoDto»:
    type: object
    properties:
      content:
        type: array
        items:
          $ref: '#/definitions/LancamentoDto'
      first:
        type: boolean
      last:
        type: boolean
      number:
        type: integer
        format: int32
      numberOfElements:
        type: integer
        format: int32
      size:
        type: integer
        format: int32
      sort:
        $ref: '#/definitions/Sort'
      totalElements:
        type: integer
        format: int64
      totalPages:
        type: integer
        format: int32
  Sort:
    type: object
  FuncionarioDto:
    type: object
    properties:
      email:
        type: string
      id:
        type: integer
        format: int64
      nome:
        type: string
      qtdHorasAlmoco:
        $ref: '#/definitions/Optional«string»'
      qtdHorasTrabalhoDia:
        $ref: '#/definitions/Optional«string»'
      senha:
        $ref: '#/definitions/Optional«string»'
      valorHora:
        $ref: '#/definitions/Optional«string»'